version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://privguard:supersecret123@pgbouncer:6432/vaultdb
      - DB_PORT=6432
      - REDIS_URL=redis:6379
      - PORT=8080
      - RUN_MIGRATIONS=true
      - WEBAUTHN_RPID=localhost
      - WEBAUTHN_RP_NAME=PrivGuard
      - WEBAUTHN_RP_ORIGINS=http://localhost:5173
    volumes:
      - ./.env:/app/.env:ro
      - ~/.aws:/root/.aws:ro
    depends_on:
      - postgres
      - redis
      - pgbouncer
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: privguard
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: vaultdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  pgbouncer:
    image: edoburu/pgbouncer
    ports:
      - "6432:6432"
    environment:
      DB_USER: privguard
      DB_PASSWORD: supersecret123
      DB_NAME: vaultdb
      DB_HOST: postgres
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    depends_on:
      - postgres

volumes:
  pgdata:
  redisdata:
